spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cyg
    username: root           
    password:
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: create-drop
        naming: 
          strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties: 
      hibernate:  
        dialect: org.hibernate.dialect.MySQL5Dialect          

  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    
